name: Reusable Gitleaks

on:
  workflow_call:
    inputs:
      enforce_on_pr:
        description: "Falhar PR se houver vazamentos"
        type: boolean
        default: true
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # (Opcional, para depuração rápida)
      # - name: Assert GITHUB_TOKEN exists
      #   run: |
      #     if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
      #       echo "GITHUB_TOKEN não está disponível no called workflow"; exit 1
      #     fi

      - name: Run Gitleaks (v2)
        id: gl
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITLEAKS_CONFIG: .github/gitleaks.toml  # se quiser usar config custom

      - name: Enforce on PR (fail if leaks)
        if: ${{ inputs.enforce_on_pr && github.event_name == 'pull_request' && steps.gl.outcome == 'failure' }}
        run: |
          echo "Gitleaks encontrou vazamentos. Falhando o PR."
          exit 1
