name: reusable-gitleaks

on:
  workflow_call:
    inputs:
      enforce_on_pr:
        description: "Falhar PR se houver vazamentos "
        type: boolean
        default: true
        required: false

permissions:
  contents: read
  pull-requests: write   # permite comentar no PR

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # necessário p/ comparar base/head em PRs

      # ⚠️ NADA de "with: args". Use env conforme o v2 exige.
      - name: Run Gitleaks
        id: gl
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true            # deixamos passar e decidimos após
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        # OBRIGATÓRIO no v2
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}  # só p/ orgs
          # GITLEAKS_CONFIG: .github/gitleaks.toml             # opcional

      - name: Enforce on PR (fail if leaks)
        if: ${{ inputs.enforce_on_pr && github.event_name == 'pull_request' && steps.gl.outcome == 'failure' }}
        run: |
          echo "Gitleaks encontrou vazamentos. Falhando o PR."
          exit 1
