name: reusable-gitleaks

on:
  workflow_call:
    inputs:
      enforce_on_pr:
        description: "Falhar PR se segredos forem encontrados"
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | bash -s -- -b /usr/local/bin
          gitleaks version

      - name: Run Gitleaks (generate SARIF)
        id: gitleaks
        continue-on-error: true
        run: |
          set +e
          gitleaks detect \
            --source . \
            --redact \
            --report-format sarif \
            --report-path gitleaks.sarif
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          set -e

      - name: Upload SARIF (Gitleaks)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks

      - name: Enforce on PRs (fail if secrets found)
        if: ${{ inputs.enforce_on_pr && github.event_name == 'pull_request' && steps.gitleaks.outputs.exit_code == '1' }}
        run: |
          echo "Gitleaks encontrou segredos neste PR." >&2
          exit 1
